name: mapping
channels:
  - http://ssb.stsci.edu/astroconda
  - defaults
  - conda-forge
dependencies:
  - cython
  - numpy
  - python=3.9
  - pymc3
  - matplotlib
  - netcdf4
  - pandas
  - scipy
  - jupyterlab
